### PR TITLE
refactor: Remove UMA interfaces lookup

### PR DESCRIPTION
**Pull request by pxrl**
These names change very rarely, and we only have need for a small number of the complete set.

### CODE REVIEW

**Review by nicholaspai — COMMENTED** [review]
@james-a-morris can you look at this and make sure we don't overwrite this in the SDK changes?

**Comment by pxrl** [comment]
nb. We could alternatively define this centrally somewhere

> @james-a-morris can you look at this and make sure we don't overwrite this in the SDK changes?

Ah good call, maybe this is migrated to sdk anyway.

**Review by mrice32 — APPROVED** [review]
LGTM!

**Comment by pxrl** [comment]
Part of this PR will be moved to sdk-v2, so I have re-proposed that part here: https://github.com/across-protocol/sdk-v2/pull/417.

**Review by james-a-morris — APPROVED** [review]
LGTM - this is now reflected in the SDK

**Pull request merged**
