### PR TITLE
improve(ProfitClient): Simulate v3 fills

### PR DESCRIPTION
**Pull request by pxrl**
The ProfitClient has, until now, used v2 fill estimates for its profitability calculations. This change upgrades to using v3 fills, which are very slightly less expensive and should improve the relayer's perceived profitability when evaluating fills.

This is a pre-requisite for deprecating fillRelay() in the contracts.

### CODE REVIEW

**Comment by pxrl** [comment]
nb. I had to resubmit this PR from scratch because I hosed up my remote branch. This one is clean.

**Review by nicholaspai — APPROVED** [review]

**Comment by nicholaspai** [comment]
> The ProfitClient has, until now, used v2 fill estimates for its profitability calculations. This change upgrades to using v3 fills, which are very slightly less expensive and should improve the relayer's perceived profitability when evaluating fills.
> 
> This is a pre-requisite for deprecating fillRelay() in the contracts.

How different are the gas costs?

**Comment by pxrl** [comment]
> > The ProfitClient has, until now, used v2 fill estimates for its profitability calculations. This change upgrades to using v3 fills, which are very slightly less expensive and should improve the relayer's perceived profitability when evaluating fills.
> > This is a pre-requisite for deprecating fillRelay() in the contracts.
> 
> How different are the gas costs?

The estimates are pretty similar to what we have now (after the fix yesterday), but in practice I think we're usually saving about 5 - 10k gas on v3 fills vs. v2, on mainnet.

**Comment by pxrl** [comment]
> This logic follows our API - I wonder if we should dump the simulation into the SDK as a util

idk - it's already there for the most part so I'm not sure there's much more to save.

**Pull request merged**
