### PR TITLE
feat(relayer): Support ignoring FilledV3Relay events

### PR DESCRIPTION
**Pull request by pxrl**
This commit makes the SpokePoolClient FilledV3Relay query optional, subject to the ACCEPT_INVALID_FILLS env var being defined true. This ensures that the behaviour is opt-in.

This is enabled by the recent change to query the fill status of all outstanding deposits. Since there's no need to submit the LP fee onchain in Across v3, the risks of opting into this setting are significantly reduced, whilst the benefits are:
- Reduced SpokePoolClient update times.
- Reduced overheads in matchind deposits with fills.

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]
Nice!

**Review by mrice32 — APPROVED** [review]
LGTM!

**Review by mrice32 — COMMENTED** [review]
Mentioned IRL, but repeating here: will this cause any issues with the relayer determining what refunds it expects in the next bundle?

**Comment by pxrl** [comment]
> Mentioned IRL, but repeating here: will this cause any issues with the relayer determining what refunds it expects in the next bundle?

Really good consideration - it would.

It's a useful feature for third-parties to have so I think it's probably worth having, but I wonder if it should also be conditional on inventory management being disabled. I've marked it `do not merge` for the time being and will think over it for a little while.

**Comment by nicholaspai** [comment]
We can probably re review this again after changing how bundle refunds are computed in the InventoryManager. If we can fetch them from Arweave then this PR can be useful even with InventoryManager enabled

**Review by nicholaspai — CHANGES_REQUESTED** [review]
do not merge yet until bundle data can be fetched without using FilledV3Relay events

**Review by nicholaspai — APPROVED** [review]
I think we can evaluate this after local testing now that we load most bundle data from arweave. However, there is still a case where we'd want to comute bundles from events when there is no bundle pending. This happens in the short window (~15 mins max) between last bundle execution and next bundle proposed.

This PR would cause the Inventory Manager to not count any bundle refunds in that time, which probably is not a big deal and worth the speed up if it is signficiant

**Comment by nicholaspai** [comment]
> I think we can evaluate this after local testing now that we load most bundle data from arweave. However, there is still a case where we'd want to comute bundles from events when there is no bundle pending. This happens in the short window (~15 mins max) between last bundle execution and next bundle proposed.
> 
> 
> 
> This PR would cause the Inventory Manager to not count any bundle refunds in that time, which probably is not a big deal and worth the speed up if it is signficiant

I think this pr is now intractable if we're going to go with the bundle refund approximation approach in #1382

**Comment by pxrl** [comment]
> > I think we can evaluate this after local testing now that we load most bundle data from arweave. However, there is still a case where we'd want to comute bundles from events when there is no bundle pending. This happens in the short window (~15 mins max) between last bundle execution and next bundle proposed.
> > This PR would cause the Inventory Manager to not count any bundle refunds in that time, which probably is not a big deal and worth the speed up if it is signficiant
> 
> I think this pr is now intractable if we're going to go with the bundle refund approximation approach in #1382

Yep, agreed. Time for it to be closed.

**Pull request closed without merging**
